"""In-dialog help: a condensed version of docs/USER-GUIDE.md.

Written in the plugin authors' voice; paraphrases (and cites) the
Cartographic Perspectives article rather than quoting it.
"""

HELP_HTML = ("<h2>What this plugin makes</h2> <p>Mapping several attributes "
             "of the same areas at once is a long-standing challenge of "
             "thematic cartography, and it has partial answers already: "
             "multivariate choropleths (bivariate and trivariate colour "
             "schemes) blend two or three attributes into a single symbology, "
             "though their legends must be learned and their ceiling arrives "
             "quickly. This plugin takes a different route. It lays a small "
             "repeating pattern across your study area and colours each kind "
             "of shape in it (each <i>element</i>, labelled a, b, c&hellip;) "
             "by its own attribute, with its own ordinary symbology, so each "
             "variable stays individually legible while sharing the one "
             "map.</p> <h2>A way of working</h2> <p>Iteration is fast, and "
             "live update follows your changes. Begin with one polygon layer "
             "in the projected CRS you mean to publish in. Choose the number "
             "of variables you want to be able to display and choose a "
             "pattern. Rough in a design with the spacing kept coarse. Assign "
             "variables and colours, refine rotation and insets, and tighten "
             "the spacing last. A final spacing near the typical width of "
             "your polygons means the smallest polygons will miss some "
             "elements at any single spacing but may be a useful "
             "compromise.</p><p>The result is a group of ordinary QGIS "
             "layers: one per element, one more for any element whose column "
             "has blanks, and the region outlines if you asked for them. You "
             "can continue to edit here or return to the main part of QGIS "
             "to edit more.</p><h2>The "
             "switches</h2> <p><i>Join data using whole tileable</i> has "
             "every element in a unit take data from the same area, so units "
             "read as coherent local summaries; left off, each tile follows "
             "the area it overlaps most, which is more faithful tile by tile "
             "but lets a unit near a boundary mix its sources (for weaves we "
             "generally leave it off). <i>Clip by map units</i> gives a tidy "
             "outline at the cost of fragmented edge tiles and speed; the "
             "ragged default sits more comfortably with the pattern as a "
             "design. <i>Use tileable as icon</i> places one unit per "
             "polygon, a gentler multivariate symbol that pairs well with the "
             "outlines layer. <i>Warn about lack of legibility in colour "
             "choices</i> checks, after each map, whether any two elements "
             "use colours a reader may not tell apart, in ordinary vision and "
             "for the red-green deficiencies. It is off by default and "
             "changes nothing about the map; turn it on once the design is "
             "close to settled.</p> <h2>Regenerating and output</h2> <p>A "
             "first map appears of its own accord once a layer and variables "
             "are in place. Generate (and live update) then replace the "
             "previous result in place, and styling you have refined by hand "
             "is kept unless you change that element's assignment in the "
             "dialog. <i>Create as new group</i> keeps a previous attempt for "
             "comparison. <i>Save to GeoPackage</i> writes all element "
             "layers, with their symbology, into one shareable file. Layer "
             "identities change on regeneration, so re-pick layers in print "
             "layouts afterwards.</p> <h2>Further reading</h2> <p>The "
             "thinking behind the technique, with worked examples:<br> "
             "O'Sullivan, D., &amp; Bergmann, L. (2026). Using MapWeaver to "
             "make tiled and woven maps of multivariate thematic data. "
             "<i>Cartographic Perspectives, 108</i>, 41&ndash;52. <a "
             "href=\"https://doi.org/10.14714/CP108.2109\">doi:10.14714/CP108.2109</a><br> "
             "O'Sullivan, D., &amp; Bergmann, L. Tilings and weaves for "
             "multivariate mapping. Manuscript under review.</p> <p>Library "
             "and examples: <a "
             "href=\"https://github.com/DOSull/weavingspace\">github.com/DOSull/weavingspace</a>. "
             "If you would like to make maps like these outside QGIS, "
             "MapWeaver is a browser-based tool built on the same library: <a "
             "href=\"https://dosull.github.io/mapweaver/app/\">dosull.github.io/mapweaver/app</a>. "
             "We welcome your examples, questions, and reports of anything "
             "that surprises you.</p>")
