#!/usr/bin/env python3
"""Keep the published content honest at release time.

    python3 tools/sync_release_content.py [--fix] [--since EPOCH]

A release does not only produce a zip. It also publishes a README, a
project page, a citation file, and a set of images that claim to show
what the plugin currently looks like and produces. Those go stale
silently: a control moves, a version bumps, a vendored library
changes, and the published material keeps describing the software as
it was. This step checks the claims and mends the mechanical ones.

What it MENDS (with --fix), because the correct value is not a matter
of judgement:

  * the version and release date in CITATION.cff.

What it REPORTS but will not touch, because the right words are a
human decision and quietly rewriting prose at release time is how
documentation turns to mush:

  * a changelog with no entry for this version;
  * images referenced by README.md or docs/index.html that do not
    exist, or that were not regenerated during this release;
  * relative links pointing at files that are not there;
  * a vendored-library version claimed in prose that disagrees with
    the stamp the vendoring tool wrote;
  * repository and page URLs in the published files that disagree with
    metadata.txt.

Args (command line):
  --fix: apply the mechanical corrections. Without it, everything is
    reported and nothing is written, which is the right mode for a
    check run by hand.
  --since: unix timestamp; images older than this are treated as not
    having been regenerated by the current release.

Exit status:
  0 when everything agrees (or was mended), 1 when something needs a
  person. release.py stops on 1, before it commits anything.
"""
import argparse
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

PUBLISHED = ["README.md", os.path.join("docs", "index.html")]


def read(path):
  """The whole text of one file in the repository.

  Args:
    path: a path relative to the repository root, so every check here
      reads the tree being released rather than whatever directory
      the tool happened to be started from.

  Returns:
    The file's contents as text. Nothing is written. A missing file
    raises OSError, so the checks that expect one may be absent
    (CITATION.cff, the vendor stamp) test for it themselves first and
    report its absence as a problem in its own right.
  """
  with open(os.path.join(ROOT, path), encoding="utf-8") as handle:
    return handle.read()


def metadata():
  """The plugin's own metadata, as a dict of the simple fields.

  Returns:
    A dict of field name to value for the single-line fields, plus
    "changelog" and "about" as whole blocks. Continuation lines in
    metadata.txt are indented, which is how the two multi-line fields
    are recognised.
  """
  fields, current = {}, None
  for line in read(os.path.join("weavingspace_qgis", "metadata.txt")).splitlines():
    if line.startswith(";") or not line.strip():
      continue
    if re.match(r"^\w+=", line):
      current, _, value = line.partition("=")
      fields[current] = value
    elif current and line.startswith((" ", "\t")):
      fields[current] += "\n" + line.strip()
  return fields


def sync_citation(version, fix):
  """Bring CITATION.cff's version and date into line with the plugin.

  Args:
    version: the version being released.
    fix: whether to write the file or only report.

  Returns:
    A list of problems, empty when the file already agreed or was
    mended. The release date is today's, since that is what releasing
    means.
  """
  path = os.path.join(ROOT, "CITATION.cff")
  if not os.path.exists(path):
    return ["CITATION.cff is missing"]
  text = read("CITATION.cff")
  today = time.strftime("%Y-%m-%d")
  wanted = [(r"(?m)^version:\s*.*$", f"version: {version}"),
            (r"(?m)^date-released:\s*.*$", f"date-released: '{today}'")]
  updated = text
  for pattern, replacement in wanted:
    updated = re.sub(pattern, replacement, updated)
  if updated == text:
    return []
  if not fix:
    return ["CITATION.cff does not name this version (run with --fix)"]
  with open(path, "w", encoding="utf-8") as handle:
    handle.write(updated)
  print(f"  mended CITATION.cff: version {version}, released {today}")
  return []


def check_changelog(fields, version):
  """The plugin manager shows a changelog; it must mention this release.

  Args:
    fields: the parsed metadata.txt as metadata() returns it. The
      "changelog" entry is the whole block, continuation lines
      included, which is why a plain substring test finds an entry
      wherever in the block it sits.
    version: the version being released.

  Returns:
    An empty list when the changelog names this version, otherwise a
    single problem. Nothing is written: what a user would notice
    about a release is the one claim here that cannot be derived from
    anything else in the tree, and a line generated to satisfy the
    check would read like one.
  """
  entry = fields.get("changelog", "")
  if version in entry:
    return []
  return [f"metadata.txt has no changelog entry for {version}; write one "
          f"line saying what a USER would notice about this release"]


def check_images(since):
  """Every published image exists, and was refreshed by this release.

  Args:
    since: unix timestamp of the moment this release began.

  Returns:
    A list of problems. Freshness matters because these images are
    the plugin's claim about what it currently looks like: a dialog
    grab from three versions ago is a picture of software that no
    longer exists.
  """
  problems = []
  referenced = set()
  for path in PUBLISHED:
    text = read(path)
    for match in re.finditer(r"(?:docs/)?(img/[\w.\-]+\.png)", text):
      referenced.add(match.group(1))
  if not referenced:
    return ["neither README.md nor docs/index.html shows any image"]
  for name in sorted(referenced):
    full = os.path.join(ROOT, "docs", name)
    if not os.path.exists(full):
      problems.append(f"{name} is shown in the published pages but does "
                      f"not exist")
      continue
    # Figures reproduced from the published article are fixed: they
    # show what the technique produced in print, and regenerating them
    # would mean altering someone's published work. Only OUR renders
    # are expected to be retaken each release.
    if os.path.basename(name).startswith("paper-"):
      continue
    # The pattern grid is exempt for a different reason, and it is
    # worth keeping the two apart. A paper figure is fixed because
    # regenerating it would alter somebody's published work. The grid
    # is fixed because it shows the CATALOGUE of families rather than
    # the current renderer's output: it changes when a family is added
    # or the palette is rethought, not when the plugin changes. Redraw
    # it deliberately with tools/make_pattern_grid.py, which documents
    # every knob. Regenerating it per release would put a rebuilt PNG
    # in every release commit and make each release need the reference
    # environment present. (User instruction, 2026-08-12.)
    if os.path.basename(name) in NOT_RETAKEN_EACH_RELEASE:
      continue
    if since and os.path.getmtime(full) < since:
      age = (time.time() - os.path.getmtime(full)) / 86400
      problems.append(
        f"docs/{name} was not regenerated by this release (last written "
        f"{age:.0f} day(s) ago); run tools/make_site_images.py so the "
        f"published pictures show the current plugin")
  return problems


# Published images that are NOT expected to be retaken by a release,
# each for a reason written at the check that reads this.
NOT_RETAKEN_EACH_RELEASE = {"patterns.png"}


def check_links():
  """Relative links in the published files point at things that exist."""
  problems = []
  for path in PUBLISHED:
    text = read(path)
    targets = re.findall(r"\]\(([^)#:]+)\)", text)          # markdown
    targets += re.findall(r'href="([^"#:]+)"', text)        # html
    for target in targets:
      if target.startswith(("http", "mailto", "//", "#")):
        continue
      base = ROOT if path == "README.md" else os.path.join(ROOT, "docs")
      if not os.path.exists(os.path.join(base, target)):
        problems.append(f"{path} links to {target}, which does not exist")
  return problems


def check_vendor_claims():
  """Prose claims about the vendored library match the recorded stamp."""
  stamp_path = os.path.join(ROOT, "weavingspace_qgis", "vendor",
                            "VENDOR-VERSION.txt")
  if not os.path.exists(stamp_path):
    return ["weavingspace_qgis/vendor/VENDOR-VERSION.txt is missing; "
            "re-run tools/vendor_weavingspace.py so the vendored "
            "version is recorded rather than only described"]
  with open(stamp_path, encoding="utf-8") as handle:
    stamp = handle.read().strip()
  version = stamp.split()[0]
  problems = []
  for path in ("README.md", "MAINTAINING.md", "CLAUDE.md"):
    text = read(path)
    claimed = set(re.findall(r"upstream v?(\d+\.\d+\.\d+(?:\.\d+)?)", text))
    for claim in claimed:
      if claim != version:
        problems.append(
          f"{path} says the vendored library is upstream {claim}, but "
          f"the vendoring tool recorded {version}")
  return problems


def check_urls(fields):
  """The published files point at the repository metadata.txt names."""
  problems = []
  for field in ("repository", "homepage"):
    url = fields.get(field, "").rstrip("/")
    if not url:
      problems.append(f"metadata.txt has no {field} URL")
      continue
    if not any(url in read(path) for path in PUBLISHED):
      problems.append(f"metadata.txt gives {field} as {url}, which "
                      f"neither README.md nor the project page mentions")
  return problems


def main():
  """Audit every claim the published files make, and mend the mechanical ones.

  Returns:
    0 when the published content agrees with this version (or was
    mended), 1 when something needs a person, with each problem
    printed. release.py stops on 1, before it commits, so a page
    describing a version other than the one being released never
    reaches a reader.

  Only CITATION.cff is ever written, and only with --fix; the version
  and release date there have exactly one correct value. Everything
  else -- a missing changelog entry, a stale image, a broken link, a
  vendored version claimed in prose, a repository URL -- is reported
  and left alone, because rewriting published prose automatically at
  release time is how documentation turns to mush.
  """
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--fix", action="store_true")
  parser.add_argument("--since", type=float, default=0)
  parser.add_argument(
    "--check", action="store_true",
    help="report only what needs a PERSON, skipping the one thing a "
         "release mends by itself. This is the form CI can run.")
  args = parser.parse_args()

  fields = metadata()
  version = fields.get("version", "").strip()
  problems = []
  # The citation's version has exactly one correct value and --fix
  # writes it, so between releases it legitimately names the LAST
  # released version and this check is legitimately unhappy. Gating a
  # push on that would be red by design, and a gate that is red by
  # design is one people stop reading -- the same reason the visual
  # gallery stays out of CI. --check therefore asks only the
  # questions whose answer is somebody's WORDS: a missing changelog
  # entry, a stale image, a broken link, a vendored version claimed
  # in prose, a repository URL. Those are wrong the moment they are
  # written, and worth learning on the push that wrote them rather
  # than eighty minutes into a release. (2026-08-11.)
  if not args.check:
    problems += sync_citation(version, args.fix)
  problems += check_changelog(fields, version)
  problems += check_images(args.since)
  problems += check_links()
  problems += check_vendor_claims()
  problems += check_urls(fields)

  if problems:
    print(f"{len(problems)} thing(s) the published content gets wrong:\n")
    for problem in problems:
      print(f"  {problem}")
    print("\nThese are claims made to readers. Fix the words, or the "
          "thing they describe.")
    return 1
  print(f"published content agrees with v{version}: "
        + ("changelog, images, links, vendored version and URLs "
           "(citation not checked: --check)" if args.check else
           "citation, changelog, images, links, vendored version "
           "and URLs"))
  return 0


if __name__ == "__main__":
  sys.exit(main())
